apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastclaw.fullname" . }}
  labels:
    {{- include "fastclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.adminToken | quote }}
  db-password: {{ include "fastclaw.dbPassword" . | quote }}
